### ISSUE TITLE
[feat] SelectSentence 기능추가

### ISSUE THREAD

**Issue by wongbingg** [DDD-Community/Particle-iOS#7]
## Description

AddArticle - SelectSentence 기능 수정 및 추가

## TODO
- [x] 좌우 스와이프가 가능함을 알리는 가이드 애니메이션 추가
- [x] 이미지 위에서 텍스트 영역을 드래그 할 수 있는 기능 추가 (iOS 16 으로 배포버전 변경)
- [x] 네비게이션 타이틀에 페이지 번호 업데이트 (5페이지 까지만 가능 😭)
- [x] 각 사진에서 문장 추출 후 저장버튼 탭시 다음 사진으로 넘어가도록 적용
    - [x] 마지막 사진일 시, OrganizingSentence RIB로 넘어갈 수 있는 다음버튼 활성화

## 번외 업데이트

- PhotoPicker RIB 에서 사진선택 넘버링 로직 적용
